version: 2


sources:
  - name: DBT_HANDSON_1_SOURCES
    description: 'configuring the sources of 4 tables'
    database: ELOOK_COMMERCE
    schema: raw
    tables:
      - name: ORDERS
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: user_id
            tests:
              - relationships:
                  field: id
                  to: ref('users')
                   
      - name: ORDER_ITEMS
        columns:
          - name: product_id
            tests:
              - relationships:
                  field: id
                  to: ref('products')
      - name: PRODUCTS
        columns:
          - name: id
            tests:
              - unique
              - not_null           
      - name: USERS
        columns:
          - name: id
            tests:
              - unique
              - not_null

models:
  - name: int_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: int_orders_clean
    columns:
      - name: order_id
        tests:
          - relationships:
              field: order_id
              to: ref('stg_orders')

 
    
              